services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: feedback_db

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  flask-app:
    build: .
    container_name: flask-app
    restart: unless-stopped

    ports:
      - "5000:5000"

    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root123
      DB_NAME: feedback_db

    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data: